const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const interests = [
  "Gym",
  "Cats",
  "Dogs",
  "Food",
  "Instagram",
  "Study",
  "Football",
  "Music",
  "Movies",
  "Reading",
  "Traveling",
  "Gaming",
  "Cooking",
  "Hiking",
  "Photography",
  "Dancing",
  "Yoga",
  "Art",
  "Writing",
  "Crafts",
  "Blogging",
  "Fishing",
  "Camping",
  "Running",
  "Cycling",
  "Swimming",
  "Board Games",
  "Video Games",
  "Meditation",
  "Gardening",
  "Astronomy",
  "Bird Watching",
  "Collecting",
  "Chess",
  "Volunteering",
  "Martial Arts",
  "Parkour",
  "Rock Climbing",
  "Skateboarding",
  "Snowboarding",
  "Surfing",
  "Tennis",
  "Basketball",
  "Soccer",
  "Baseball",
  "Rugby",
  "American Football",
  "Cricket",
  "Table Tennis",
  "Badminton",
  "Bowling",
  "Golf",
  "Squash",
  "Lacrosse",
  "Field Hockey",
  "Ice Hockey",
  "Skiing",
  "Scuba Diving",
  "Snorkeling",
  "Sailing",
  "Kayaking",
  "Canoeing",
  "Rowing",
  "Fencing",
  "Archery",
  "Shooting",
  "Horseback Riding",
  "Mountain Biking",
  "Triathlon",
  "Duathlon",
  "Motorsports",
  "Esports",
  "Anime",
  "Manga",
  "Comic Books",
  "Graphic Novels",
  "Theater",
  "Opera",
  "Ballet",
  "Classical Music",
  "Jazz",
  "Blues",
  "Rock",
  "Pop",
  "Hip Hop",
  "R&B",
  "Country",
  "Folk",
  "Electronic",
  "Reggae",
  "Metal",
  "Punk",
  "Ska",
  "Dance",
  "House",
  "Techno",
];

async function main() {
  for (const interest of interests) {
    await prisma.interest.upsert({
      where: { name: interest },
      update: {},
      create: { name: interest },
    });
  }
}

main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
