name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.2.0'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
          rm -rf ~/munchmates
          git clone https://github.com/kaizen403/munchmates.git ~/munchmates
          cd ~/munchmates
          pnpm install
          pnpm run build
          pm2 delete all
          pm2 start pnpm "pnpm build && pnpm start"--name "munchmate" -- start
        EOF
